##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
LIBRARYNAME=PRE
LOADABLE_MODULE=1
CXXFLAGS=-fexceptions

include $(LEVEL)/Makefile.common
